### ISSUE TITLE
Trying Elastic exporter in Docker

### ISSUE THREAD

**Issue by dineshkumar511** [bitnami/bitnami-docker-elasticsearch-exporter#2]
Earlier i ran this exporter in a VM linux server with binary . By using following command.

[<elasticsearch-exporter-binary> --es.uri=node1 --es.uri=node2 --es.uri=node3 ..] -->this method working well.

Now I'm trying to run the exporter via Docker Container with multiple Elasticsearch nodes. When trying to run the Docker with an image , geting the following error "the --es.uri is cannot be repeated" . 
Exporter is working with only one node and showing metrics for that node only. How we can configure multiple nodes?

### Dockerfile
```Dockerfile
FROM <image>
RUN mkdir -P /dir
COPY run.sh  /dir/
ENTRYPOINT ["/dir/run.sh"]
```
### run.sh
```bash
#!/bin/bash -x
<es-exporter-binary(in container location)> --es.uri=node1 --es.uri=node2 --es.uri=node3 ..
```

So kindly let me know if i'm missing anything .

**Comment by migruiz4** [comment]
Hi @dineshkumar511,

This image uses https://github.com/prometheus-community/elasticsearch_exporter, and it looks like providing multiple `es.uri` is not supported.

> How we can configure multiple nodes?

The proper way to do it would be to have one elasticsearch-exporter per Elasticsearch node.

If you are running in Kubernetes, you could run the exporter as a sidecar container, as we do in our Kubernetes Helm Chart: https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch
